server:
  port: 8080
  servlet:
    context-path: /blog



spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  profiles:
    active: local

mybatis-plus:
  configuration:
    # mybatis配置中设置将sql日志输出到控制台
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#jwt
jwt:
  secret: cccsp_secret!